from datetime import datetime

class Alert:
    """
    Represents a security threat alert generated by rule matches in the RuleEngine.
    """
    def __init__(
        self,
        id: int,
        ruleName: str,
        attackType: str,
        sourceIp: str,
        destinationIp: str,
        severity: str,
        confidence: float,
        timestamp: datetime,
        description: str
    ):
        self.id = id
        self.ruleName = ruleName
        self.attackType = attackType
        self.sourceIp = sourceIp
        self.destinationIp = destinationIp
        self.severity = severity
        self.confidence = confidence
        self.timestamp = timestamp
        self.description = description

    def getMessage(self) -> str:
        """
        Returns a formatted, human-readable warning message summary of the alert.
        """
        time_str = self.timestamp.strftime("%Y-%m-%d %H:%M:%S")
        return (
            f"[{self.severity.upper()} ALERT #{self.id}] "
            f"{self.attackType} detected from {self.sourceIp} to {self.destinationIp} "
            f"(Rule: {self.ruleName}) | Confidence: {self.confidence:.2f} | Detected at: {time_str}"
        )

    def toDictionary(self) -> dict:
        """
        Serializes the Alert object to a Python dictionary format.
        """
        return {
            "id": self.id,
            "ruleName": self.ruleName,
            "attackType": self.attackType,
            "sourceIp": self.sourceIp,
            "destinationIp": self.destinationIp,
            "severity": self.severity,
            "confidence": self.confidence,
            "timestamp": self.timestamp.isoformat() if isinstance(self.timestamp, datetime) else self.timestamp,
            "description": self.description
        }
