"""
EmailChannel – Gửi cảnh báo qua Email (SMTP)
==============================================
Gửi email cảnh báo bảo mật thông qua SMTP server.

Hỗ trợ:
  - Gmail (smtp.gmail.com:587 với TLS)
  - Outlook (smtp.office365.com:587)
  - Bất kỳ SMTP server nào

Cấu hình (config.yaml):
  notifications:
    email:
      enabled: true
      smtp_server: "smtp.gmail.com"
      port: 587
      sender: "alert@sentinel.ai"
      receiver: "admin@company.com"
      password: "YOUR_APP_PASSWORD"  # Dùng App Password cho Gmail

Lưu ý Gmail:
  - Không dùng mật khẩu thường, dùng App Password
  - Bật 2-Step Verification → App passwords → Tạo password mới
"""

import logging
import smtplib
import sys
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Any

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from models.alert import Alert
from notification.notificationChannelInterface import NotificationChannel

logger = logging.getLogger(__name__)


class EmailChannel(NotificationChannel):
    """
    Gửi cảnh báo bảo mật qua email thông qua SMTP.
    """

    def __init__(self, config: Dict[str, Any] = None):
        """
        Args:
            config (dict): SMTP configuration
        """
        config = config or {}
        self._enabled = config.get("enabled", False)
        self._smtp_server = config.get("smtp_server", "smtp.gmail.com")
        self._port = config.get("port", 587)
        self._sender = config.get("sender", "")
        self._receiver = config.get("receiver", "")
        self._password = config.get("password", "")

    def isEnabled(self) -> bool:
        return (self._enabled and bool(self._sender)
                and bool(self._receiver) and bool(self._password))

    def send(self, alert: Alert) -> bool:
        """
        Gửi email với thông tin Alert.

        Args:
            alert (Alert): Alert cần gửi

        Returns:
            bool: True nếu gửi thành công
        """
        if not self.isEnabled():
            return False

        try:
            # Tạo email với nội dung HTML
            msg = MIMEMultipart("alternative")
            msg["Subject"] = f"[IDS ALERT] [{alert.severity.upper()}] {alert.attackType} from {alert.sourceIp}"
            msg["From"] = self._sender
            msg["To"] = self._receiver

            # Plain text fallback
            text_body = (
                f"SECURITY ALERT\n\n"
                f"Attack Type: {alert.attackType}\n"
                f"Severity: {alert.severity.upper()}\n"
                f"Source: {alert.sourceIp}\n"
                f"Target: {alert.destinationIp}\n"
                f"Confidence: {alert.confidence:.2%}\n"
                f"Time: {alert.timestamp.strftime('%Y-%m-%d %H:%M:%S')}\n"
                f"Description: {alert.description}"
            )

            # HTML version
            html_body = f"""
            <html><body style="font-family:Arial,sans-serif;padding:20px;">
            <h2 style="color:#dc3545;">🚨 Network Security Alert</h2>
            <table style="border-collapse:collapse;width:100%">
                <tr><td style="padding:8px;background:#f8f9fa;font-weight:bold">Attack Type</td>
                    <td style="padding:8px">{alert.attackType}</td></tr>
                <tr><td style="padding:8px;background:#f8f9fa;font-weight:bold">Severity</td>
                    <td style="padding:8px;color:#dc3545;font-weight:bold">{alert.severity.upper()}</td></tr>
                <tr><td style="padding:8px;background:#f8f9fa;font-weight:bold">Source IP</td>
                    <td style="padding:8px"><code>{alert.sourceIp}</code></td></tr>
                <tr><td style="padding:8px;background:#f8f9fa;font-weight:bold">Target IP</td>
                    <td style="padding:8px"><code>{alert.destinationIp}</code></td></tr>
                <tr><td style="padding:8px;background:#f8f9fa;font-weight:bold">Confidence</td>
                    <td style="padding:8px">{alert.confidence:.2%}</td></tr>
                <tr><td style="padding:8px;background:#f8f9fa;font-weight:bold">Detected At</td>
                    <td style="padding:8px">{alert.timestamp.strftime('%Y-%m-%d %H:%M:%S')}</td></tr>
                <tr><td style="padding:8px;background:#f8f9fa;font-weight:bold">Description</td>
                    <td style="padding:8px">{alert.description}</td></tr>
            </table>
            <p style="color:#888;font-size:12px;margin-top:20px">
                This alert was generated by NetworkSentinelAI
            </p></body></html>"""

            msg.attach(MIMEText(text_body, "plain", "utf-8"))
            msg.attach(MIMEText(html_body, "html", "utf-8"))

            # Kết nối SMTP với TLS
            with smtplib.SMTP(self._smtp_server, self._port, timeout=10) as server:
                server.ehlo()
                server.starttls()
                server.login(self._sender, self._password)
                server.sendmail(self._sender, self._receiver, msg.as_string())

            logger.info(f"Email: Gửi alert #{alert.id} đến {self._receiver} thành công")
            return True

        except smtplib.SMTPAuthenticationError:
            logger.error("Email: Xác thực thất bại. Kiểm tra sender/password trong config.")
            return False
        except Exception as e:
            logger.error(f"Email: Lỗi gửi alert #{alert.id}: {e}")
            return False
